# ==================================================================================== #
[table]

# Number of table dimensions to create
ndim = 1 

# Grid points for each table dimension
ngrid = 20 

# Filename prefix for output
outfile_prefix = "peletable" 

