name: CMLM-CI

permissions:
  contents: read

on:
   workflow_dispatch:
   push:
     branches: [development]
   pull_request:
     branches: [development]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']
        poetry-version: ['1.4.2']
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{matrix.poetry-version}}
      - name: Install Dependencies using Poetry
        run: poetry install
      - name: Formatting with black
        run: poetry run black --check cmlm/
      - name: Sort imports with isort
        run: poetry run isort --check-only --diff cmlm/
      - name: Lint with flake8
        run: poetry run flake8 cmlm/
  Codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Dependencies
        run: |
          # Install Python packages
          python -m pip install --upgrade pip
          pip install codespell
      - name: Run codespell
        run: codespell cmlm/ docs/ --skip="*.bib,*.csv,*.pdf"
        #run: codespell --skip="*.bib,*.csv,*.pdf"